# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "rspec", "~> 3.10"
gem "tty-prompt"
gem "tty-table"
gem "tty-box"
gem "colorize", "~> 0.8.1"
gem "pastel"
gem "tty-font"
gem 'postmark'
gem 'dotenv'
